# Deploy Voter Stack locally

version: '3.0'

services:
  client:
    image: garystafford/voter-client:rabbitmq-0.4.55
    depends_on:
    - gateway
    hostname: client
    ports:
    - "9000:8080/tcp"
    networks:
    - demo_overlay_net

  gateway:
    image: garystafford/voter-api-gateway:rabbitmq
    depends_on:
    - election
    - candidate
    - voter
    hostname: voter-api-gateway
    ports:
    - "8080:8080/tcp"
    networks:
    - demo_overlay_net

  election:
    image: garystafford/election-service:rabbitmq-0.4.29
    depends_on:
    - mongodb
    - rabbitmq
    hostname: election
    ports:
    - "8095:8080/tcp"
    command: "java -Dspring.profiles.active=${ACTIVE_PROFILE} \
      -Dlogging.level.root=DEBUG \
      -Djava.security.egd=file:/dev/./urandom \
      -jar election/election-service.jar"
    networks:
    - demo_overlay_net

  candidate:
    image: garystafford/candidate-service:rabbitmq-0.4.112
    depends_on:
    - mongodb
    - rabbitmq
    hostname: candidate
    ports:
    - "8097:8080/tcp"
    command: "java -Dspring.profiles.active=${ACTIVE_PROFILE} \
      -Dlogging.level.root=DEBUG \
      -Djava.security.egd=file:/dev/./urandom \
      -jar candidate/candidate-service.jar"
    networks:
    - demo_overlay_net

  voter:
    image: garystafford/voter-service:rabbitmq-0.4.234
    depends_on:
    - mongodb
    - rabbitmq
    hostname: voter
    ports:
    - "8099:8080/tcp"
    command: "java -Dspring.profiles.active=${ACTIVE_PROFILE} \
      -Dlogging.level.root=DEBUG \
      -Djava.security.egd=file:/dev/./urandom \
      -jar voter/voter-service.jar"
    networks:
    - demo_overlay_net

  mongodb:
    image: mongo:latest
    command:
    - --smallfiles
    hostname: mongodb
    ports:
    - "27017:27017/tcp"
    volumes:
    - demo_data_vol:/data/db
    networks:
    - demo_overlay_net

  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    ports:
    - "5672:5672/tcp"
    - "15672:15672/tcp"
    volumes:
    - demo_data_vol:/data/db
    networks:
    - demo_overlay_net

networks:
  demo_overlay_net:

volumes:
  demo_data_vol:
